CREATE TABLE "T_NODE" (
  "NODEID" VARCHAR2(32),
  "JBPM_NODEID" NUMBER(19, 0),
  "PDID" VARCHAR2(32),
  "NODETYPE" CHAR(1),
  "BUSINESSSTATE" VARCHAR2(32),
  "LEAVEDELEGATION" VARCHAR2(32),
  "ENTERDELEGATION" VARCHAR2(32),
  "ISASSIGNAGAIN" CHAR(1) DEFAULT 'N',
  "ISSUPERIOR" CHAR(1) DEFAULT 'N',
  "SWIMLANEID" VARCHAR2(32),
  "EXPANDNODEID" VARCHAR2(32),
  "NODENAME" VARCHAR2(50),
  "NOTICETIMELIMIT" VARCHAR2(50)
)
